# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri May 23 13:25:44 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 608)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 651, 25))
        self.menubar.setObjectName("menubar")
        self.menuTiedostot = QtGui.QMenu(self.menubar)
        self.menuTiedostot.setObjectName("menuTiedostot")
        self.menuMuokkaa = QtGui.QMenu(self.menubar)
        self.menuMuokkaa.setObjectName("menuMuokkaa")
        self.menuOhje = QtGui.QMenu(self.menubar)
        self.menuOhje.setObjectName("menuOhje")
        self.menuN_yt = QtGui.QMenu(self.menubar)
        self.menuN_yt.setObjectName("menuN_yt")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionUusi_projekti = QtGui.QAction(MainWindow)
        self.actionUusi_projekti.setObjectName("actionUusi_projekti")
        self.actionAvaa = QtGui.QAction(MainWindow)
        self.actionAvaa.setObjectName("actionAvaa")
        self.actionTallenna = QtGui.QAction(MainWindow)
        self.actionTallenna.setObjectName("actionTallenna")
        self.actionTalenna_nimell = QtGui.QAction(MainWindow)
        self.actionTalenna_nimell.setObjectName("actionTalenna_nimell")
        self.actionLopeta = QtGui.QAction(MainWindow)
        self.actionLopeta.setObjectName("actionLopeta")
        self.actionAsetukset = QtGui.QAction(MainWindow)
        self.actionAsetukset.setObjectName("actionAsetukset")
        self.actionTiedot = QtGui.QAction(MainWindow)
        self.actionTiedot.setObjectName("actionTiedot")
        self.actionASetukste = QtGui.QAction(MainWindow)
        self.actionASetukste.setObjectName("actionASetukste")
        self.actionKeskit = QtGui.QAction(MainWindow)
        self.actionKeskit.setObjectName("actionKeskit")
        self.actionAseta = QtGui.QAction(MainWindow)
        self.actionAseta.setObjectName("actionAseta")
        self.menuTiedostot.addAction(self.actionUusi_projekti)
        self.menuTiedostot.addAction(self.actionAvaa)
        self.menuTiedostot.addSeparator()
        self.menuTiedostot.addAction(self.actionTallenna)
        self.menuTiedostot.addAction(self.actionTalenna_nimell)
        self.menuTiedostot.addSeparator()
        self.menuTiedostot.addAction(self.actionLopeta)
        self.menuMuokkaa.addAction(self.actionASetukste)
        self.menuOhje.addAction(self.actionTiedot)
        self.menuN_yt.addAction(self.actionKeskit)
        self.menuN_yt.addAction(self.actionAseta)
        self.menubar.addAction(self.menuTiedostot.menuAction())
        self.menubar.addAction(self.menuMuokkaa.menuAction())
        self.menubar.addAction(self.menuN_yt.menuAction())
        self.menubar.addAction(self.menuOhje.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Ijonmap", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTiedostot.setTitle(QtGui.QApplication.translate("MainWindow", "Tiedostot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMuokkaa.setTitle(QtGui.QApplication.translate("MainWindow", "Muokkaa", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOhje.setTitle(QtGui.QApplication.translate("MainWindow", "Ohje", None, QtGui.QApplication.UnicodeUTF8))
        self.menuN_yt.setTitle(QtGui.QApplication.translate("MainWindow", "Näytä", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUusi_projekti.setText(QtGui.QApplication.translate("MainWindow", "Uusi projekti", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAvaa.setText(QtGui.QApplication.translate("MainWindow", "Avaa", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTallenna.setText(QtGui.QApplication.translate("MainWindow", "Tallenna", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTalenna_nimell.setText(QtGui.QApplication.translate("MainWindow", "Talenna nimellä", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLopeta.setText(QtGui.QApplication.translate("MainWindow", "Lopeta", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAsetukset.setText(QtGui.QApplication.translate("MainWindow", "Asetukset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTiedot.setText(QtGui.QApplication.translate("MainWindow", "Tiedot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionASetukste.setText(QtGui.QApplication.translate("MainWindow", "Asetukset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeskit.setText(QtGui.QApplication.translate("MainWindow", "Keskitä", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAseta.setText(QtGui.QApplication.translate("MainWindow", "Aseta", None, QtGui.QApplication.UnicodeUTF8))

